name: TST_DOC
channels:
  - defaults
dependencies:
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - libcxx=10.0.0=1
  - libedit=3.1.20191231
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1h
  - pip=20.2.4
  - python=3.8.5
  - readline=8.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - alabaster==0.7.12
    - astroid==2.4.2
    - atpbar==1.1.3
    - attrs==20.2.0
    - autogluon==0.0.12
    - babel==2.8.0
    - bcrypt==3.2.0
    - boto3==1.16.3
    - botocore==1.19.3
    - catboost==0.23.2
    - cffi==1.14.3
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.6.0
    - commonmark==0.8.1
    - configspace==0.4.10
    - cryptography==3.1.1
    - cycler==0.10.0
    - cython==0.29.21
    - dask==2.30.0
    - decorator==4.4.2
    - distributed==2.30.0
    - docutils==0.16
    - funcy==1.15
    - future==0.18.2
    - gluoncv==0.8.0
    - gluonnlp==0.9.1
    - heapdict==1.0.1
    - idna==2.10
    - imagesize==1.2.0
    - iniconfig==1.1.1
    - jinja2==2.11.2
    - jmespath==0.10.0
    - joblib==0.17.0
    - kiwisolver==1.2.0
    - latexcodec==2.0.1
    - lazy-object-proxy==1.4.3
    - liac-arff==2.5.0
    - lightgbm==2.3.1
    - llvmlite==0.34.0
    - mantichora==0.9.5
    - markupsafe==1.1.1
    - matplotlib==3.3.2
    - mock==1.0.1
    - msgpack==1.0.0
    - mxnet==1.7.0.post1
    - networkx==2.5
    - numba==0.51.2
    - numexpr==2.7.1
    - numpy==1.19.2
    - openml==0.10.2
    - oset==0.1.3
    - packaging==20.4
    - pandas==0.25.3
    - paramiko==2.7.2
    - pillow==6.2.1
    - plotly==4.12.0
    - pluggy==0.13.1
    - portalocker==2.0.0
    - psutil==5.7.2
    - py==1.9.0
    - pyaml==20.4.0
    - pybtex==0.23.0
    - pybtex-docutils==0.2.2
    - pycparser==2.20
    - pygments==2.7.1
    - pyldavis==2.1.2
    - pynacl==1.4.0
    - pyopenssl==18.0.0
    - pyparsing==2.4.7
    - pysocks==1.6.8
    - pytest==6.1.1
    - python-dateutil==2.8.1
    - python-graphviz==0.8.4
    - pytz==2020.1
    - pyyaml==5.3.1
    - readthedocs-sphinx-ext==2.1.1
    - recommonmark==0.5.0
    - regex==2020.10.23
    - requests==2.24.0
    - retrying==1.3.3
    - s3transfer==0.3.3
    - sacremoses==0.0.43
    - scikit-learn==0.22.2.post1
    - scikit-optimize==0.8.1
    - scipy==1.5.3
    - sentence-splitter==1.4
    - setuptools==41.0.1
    - six==1.15.0
    - snowballstemmer==2.0.0
    - sortedcontainers==2.2.2
    - sphinx==3.2.1
    - sphinx-autoapi==1.4.0
    - sphinx-gallery==0.2.0
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-bibtex==1.0.0
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - sphinxcontrib-svg2pdfconverter==1.1.0
    - sphinxcontrib-websupport==1.1.0
    - tabulate==0.8.7
    - tblib==1.7.0
    - toml==0.10.1
    - toolz==0.11.1
    - tornado==6.0.4
    - tqdm==4.50.2
    - typing==3.7.4.3
    - umap-learn==0.3.7
    - unidecode==1.1.1
    - urllib3==1.25.11
    - wrapt==1.12.1
    - xmltodict==0.12.0
    - zict==2.0.0


